name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/kube-news:v${{ github.run_number }}
            ${{ secrets.DOCKERHUB_USERNAME }}/kube-news:latest 
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Cloning repository
        uses: actions/checkout@v3

      - name: Setting context
        uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploying
        uses: Azure/k8s-deploy@v3.1
        with:
          action: deploy
          images: ${{ secrets.DOCKERHUB_USERNAME }}/kube-news:v${{ github.run_number }}
          manifests: ./k8s
